# Generated by Django 4.2 on 2023-04-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('item_url', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total_bids', models.IntegerField(default=0)),
                ('seller_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('search_term', models.CharField(max_length=255)),
                ('auction_category', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auction_type', models.BooleanField(default=True)),
                ('new_item', models.BooleanField(default=True)),
                ('ending_soon', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('bidding_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.auctions')),
                ('highest_bid', models.IntegerField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('average_price', models.IntegerField(blank=True, null=True)),
                ('highest_price', models.IntegerField(blank=True, null=True)),
                ('lowest_price', models.IntegerField(blank=True, null=True)),
                ('auctions', models.ManyToManyField(to='backend.auctions')),
            ],
            options={
                'unique_together': {('term', 'category')},
            },
        ),
    ]
