# Generated by Django 4.2 on 2023-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searches',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
